export const ActionTypes = {
  SET_USERS: 'SET_USERS',
  SELECTED_USERS: 'SELECTED_USERS',
  REMOVE_SELECTED_USERS: 'REMOVE_SELECTED_USERS',
  CREATE_NEW_USER_SUCCEEDED: 'CREATE_NEW_USER_SUCCEEDED',
  DELETE_USER: 'DELETE_USER',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  UPDATE_USER: 'UPDATE_USER',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
}
